// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type FooterLayoutDocumentDataSlicesSlice = FooterListSlice

type FooterLayoutDocumentDataSlices1Slice = FooterImageSlice

type FooterLayoutDocumentDataSlices2Slice = FooterListSlice

/**
 * Content for Footer Layout documents
 */
interface FooterLayoutDocumentData {
  /**
   * Slice Zone field in *Footer Layout*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_layout.slices[]
   * - **Tab**: Column 1
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FooterLayoutDocumentDataSlicesSlice> /**
   * Slice Zone field in *Footer Layout*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_layout.slices1[]
   * - **Tab**: Column 2
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices1: prismic.SliceZone<FooterLayoutDocumentDataSlices1Slice> /**
   * Slice Zone field in *Footer Layout*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_layout.slices2[]
   * - **Tab**: Column 3
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices2: prismic.SliceZone<FooterLayoutDocumentDataSlices2Slice>
}

/**
 * Footer Layout document from Prismic
 *
 * - **API ID**: `footer_layout`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterLayoutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterLayoutDocumentData>,
    'footer_layout',
    Lang
  >

type HomepageDocumentDataSlicesSlice = RichTextSlice

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    'homepage',
    Lang
  >

type LayoutDocumentDataSlicesSlice = MenuItemSlice

type LayoutDocumentDataSlices1Slice = FooterItemSlice

/**
 * Content for Layout documents
 */
interface LayoutDocumentData {
  /**
   * Call Label field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: What should the call button say?
   * - **API ID Path**: layout.call_label
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  call_label: prismic.KeyTextField

  /**
   * Call Link field in *Layout*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Where should the call button go?
   * - **API ID Path**: layout.call_link
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  call_link: prismic.LinkField

  /**
   * Slice Zone field in *Layout*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.slices[]
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LayoutDocumentDataSlicesSlice> /**
   * Privacy Label field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.privacy_label
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  privacy_label: prismic.KeyTextField

  /**
   * Privacy Link field in *Layout*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.privacy_link
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  privacy_link: prismic.LinkField

  /**
   * Slice Zone field in *Layout*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.slices1[]
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices1: prismic.SliceZone<LayoutDocumentDataSlices1Slice>
}

/**
 * Layout document from Prismic
 *
 * - **API ID**: `layout`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LayoutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LayoutDocumentData>,
    'layout',
    Lang
  >

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Domain field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.domain
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  domain: prismic.KeyTextField

  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField

  /**
   * Phone field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.phone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField

  /**
   * Site Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_meta_description: prismic.KeyTextField

  /**
   * Site Meta Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_meta_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  site_meta_image: prismic.ImageField<never>
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    'settings',
    Lang
  >

type SubMenuDocumentDataSlicesSlice = SubMenuItemSlice | SubMenuHeadingSlice

type SubMenuDocumentDataSlices1Slice = SubMenuItemSlice | SubMenuHeadingSlice

type SubMenuDocumentDataSlices2Slice = SubMenuItemSlice | SubMenuHeadingSlice

/**
 * Content for Sub Menu documents
 */
interface SubMenuDocumentData {
  /**
   * Slice Zone field in *Sub Menu*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu.slices[]
   * - **Tab**: Column 1
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SubMenuDocumentDataSlicesSlice> /**
   * Slice Zone field in *Sub Menu*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu.slices1[]
   * - **Tab**: Column 2
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices1: prismic.SliceZone<SubMenuDocumentDataSlices1Slice> /**
   * Slice Zone field in *Sub Menu*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu.slices2[]
   * - **Tab**: Column 3
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices2: prismic.SliceZone<SubMenuDocumentDataSlices2Slice>
}

/**
 * Sub Menu document from Prismic
 *
 * - **API ID**: `sub_menu`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SubMenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SubMenuDocumentData>,
    'sub_menu',
    Lang
  >

export type AllDocumentTypes =
  | FooterLayoutDocument
  | HomepageDocument
  | LayoutDocument
  | SettingsDocument
  | SubMenuDocument

/**
 * Primary content in *FooterImage → Primary*
 */
export interface FooterImageSliceDefaultPrimary {
  /**
   * Image field in *FooterImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Default variation for FooterImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterImageSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FooterImageSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *FooterImage*
 */
type FooterImageSliceVariation = FooterImageSliceDefault

/**
 * FooterImage Shared Slice
 *
 * - **API ID**: `footer_image`
 * - **Description**: FooterImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterImageSlice = prismic.SharedSlice<
  'footer_image',
  FooterImageSliceVariation
>

/**
 * Primary content in *FooterItem → Primary*
 */
export interface FooterItemSliceDefaultPrimary {
  /**
   * Heading field in *FooterItem → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_item.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField
}

/**
 * Default variation for FooterItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterItemSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FooterItemSliceDefaultPrimary>,
  never
>

/**
 * Primary content in *FooterItem → Primary*
 */
export interface FooterItemSliceMultiColumnPrimary {
  /**
   * Heading field in *FooterItem → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_item.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField

  /**
   * Multi Column Layout field in *FooterItem → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_item.primary.multi_column_layout
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  multi_column_layout: prismic.ContentRelationshipField<'footer_layout'>
}

/**
 * MultiColumn variation for FooterItem Slice
 *
 * - **API ID**: `multiColumn`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterItemSliceMultiColumn = prismic.SharedSliceVariation<
  'multiColumn',
  Simplify<FooterItemSliceMultiColumnPrimary>,
  never
>

/**
 * Slice variation for *FooterItem*
 */
type FooterItemSliceVariation =
  | FooterItemSliceDefault
  | FooterItemSliceMultiColumn

/**
 * FooterItem Shared Slice
 *
 * - **API ID**: `footer_item`
 * - **Description**: FooterItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterItemSlice = prismic.SharedSlice<
  'footer_item',
  FooterItemSliceVariation
>

/**
 * Primary content in *FooterList → Items*
 */
export interface FooterListSliceDefaultItem {
  /**
   * Label field in *FooterList → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_list.items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField

  /**
   * Link field in *FooterList → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_list.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Default variation for FooterList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterListSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<FooterListSliceDefaultItem>
>

/**
 * Slice variation for *FooterList*
 */
type FooterListSliceVariation = FooterListSliceDefault

/**
 * FooterList Shared Slice
 *
 * - **API ID**: `footer_list`
 * - **Description**: FooterList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterListSlice = prismic.SharedSlice<
  'footer_list',
  FooterListSliceVariation
>

/**
 * Primary content in *MenuItem → Primary*
 */
export interface MenuItemSliceDefaultPrimary {
  /**
   * Label field in *MenuItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField

  /**
   * Link field in *MenuItem → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Default variation for MenuItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuItemSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<MenuItemSliceDefaultPrimary>,
  never
>

/**
 * Primary content in *MenuItem → Primary*
 */
export interface MenuItemSliceWithSubMenuPrimary {
  /**
   * Label field in *MenuItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField

  /**
   * Sub Menu field in *MenuItem → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.primary.sub_menu
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  sub_menu: prismic.ContentRelationshipField<'sub_menu'>
}

/**
 * With Sub Menu variation for MenuItem Slice
 *
 * - **API ID**: `withSubMenu`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuItemSliceWithSubMenu = prismic.SharedSliceVariation<
  'withSubMenu',
  Simplify<MenuItemSliceWithSubMenuPrimary>,
  never
>

/**
 * Slice variation for *MenuItem*
 */
type MenuItemSliceVariation = MenuItemSliceDefault | MenuItemSliceWithSubMenu

/**
 * MenuItem Shared Slice
 *
 * - **API ID**: `menu_item`
 * - **Description**: MenuItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuItemSlice = prismic.SharedSlice<
  'menu_item',
  MenuItemSliceVariation
>

/**
 * Primary content in *RichText → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Rich Text field in *RichText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.primary.rich_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  rich_text: prismic.RichTextField
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<RichTextSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  'rich_text',
  RichTextSliceVariation
>

/**
 * Primary content in *SubMenuHeading → Primary*
 */
export interface SubMenuHeadingSliceDefaultPrimary {
  /**
   * Heading field in *SubMenuHeading → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_heading.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField
}

/**
 * Default variation for SubMenuHeading Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubMenuHeadingSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<SubMenuHeadingSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *SubMenuHeading*
 */
type SubMenuHeadingSliceVariation = SubMenuHeadingSliceDefault

/**
 * SubMenuHeading Shared Slice
 *
 * - **API ID**: `sub_menu_heading`
 * - **Description**: SubMenuHeading
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubMenuHeadingSlice = prismic.SharedSlice<
  'sub_menu_heading',
  SubMenuHeadingSliceVariation
>

/**
 * Primary content in *SubMenuItem → Primary*
 */
export interface SubMenuItemSliceDefaultPrimary {
  /**
   * Label field in *SubMenuItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField

  /**
   * Link field in *SubMenuItem → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Default variation for SubMenuItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubMenuItemSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<SubMenuItemSliceDefaultPrimary>,
  never
>

/**
 * Primary content in *SubMenuItem → Primary*
 */
export interface SubMenuItemSliceBoxPrimary {
  /**
   * Label field in *SubMenuItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField

  /**
   * Link field in *SubMenuItem → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField

  /**
   * Description field in *SubMenuItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField
}

/**
 * Box variation for SubMenuItem Slice
 *
 * - **API ID**: `box`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubMenuItemSliceBox = prismic.SharedSliceVariation<
  'box',
  Simplify<SubMenuItemSliceBoxPrimary>,
  never
>

/**
 * Slice variation for *SubMenuItem*
 */
type SubMenuItemSliceVariation = SubMenuItemSliceDefault | SubMenuItemSliceBox

/**
 * SubMenuItem Shared Slice
 *
 * - **API ID**: `sub_menu_item`
 * - **Description**: SubMenuItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubMenuItemSlice = prismic.SharedSlice<
  'sub_menu_item',
  SubMenuItemSliceVariation
>

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>
  }

  namespace Content {
    export type {
      FooterLayoutDocument,
      FooterLayoutDocumentData,
      FooterLayoutDocumentDataSlicesSlice,
      FooterLayoutDocumentDataSlices1Slice,
      FooterLayoutDocumentDataSlices2Slice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      LayoutDocument,
      LayoutDocumentData,
      LayoutDocumentDataSlicesSlice,
      LayoutDocumentDataSlices1Slice,
      SettingsDocument,
      SettingsDocumentData,
      SubMenuDocument,
      SubMenuDocumentData,
      SubMenuDocumentDataSlicesSlice,
      SubMenuDocumentDataSlices1Slice,
      SubMenuDocumentDataSlices2Slice,
      AllDocumentTypes,
      FooterImageSlice,
      FooterImageSliceDefaultPrimary,
      FooterImageSliceVariation,
      FooterImageSliceDefault,
      FooterItemSlice,
      FooterItemSliceDefaultPrimary,
      FooterItemSliceMultiColumnPrimary,
      FooterItemSliceVariation,
      FooterItemSliceDefault,
      FooterItemSliceMultiColumn,
      FooterListSlice,
      FooterListSliceDefaultItem,
      FooterListSliceVariation,
      FooterListSliceDefault,
      MenuItemSlice,
      MenuItemSliceDefaultPrimary,
      MenuItemSliceWithSubMenuPrimary,
      MenuItemSliceVariation,
      MenuItemSliceDefault,
      MenuItemSliceWithSubMenu,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      SubMenuHeadingSlice,
      SubMenuHeadingSliceDefaultPrimary,
      SubMenuHeadingSliceVariation,
      SubMenuHeadingSliceDefault,
      SubMenuItemSlice,
      SubMenuItemSliceDefaultPrimary,
      SubMenuItemSliceBoxPrimary,
      SubMenuItemSliceVariation,
      SubMenuItemSliceDefault,
      SubMenuItemSliceBox,
    }
  }
}
