// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  menu_item: dynamic(() => import('./MenuItem')),
  rich_text: dynamic(() => import('./RichText')),
  sub_menu_heading: dynamic(() => import('./SubMenuHeading')),
  sub_menu_item: dynamic(() => import('./SubMenuItem')),
}
